# Generated by Django 5.2.5 on 2025-08-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='stance',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
